apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: ibm-rest-dbparms.txt
spec:
  type: setdbparms
  contents: bXFzaXNldGRicGFybXMgLXcgL2hvbWUvYWNldXNlci9hY2Utc2VydmVyIC1uIHNldGRicGFybXM6OnRydXN0c3RvcmUgLXUgInRydXN0c3RvcmVwd2QiIC1wIHBhc3N3MHJkCm1xc2lzZXRkYnBhcm1zIC13IC9ob21lL2FjZXVzZXIvYWNlLXNlcnZlciAtbiBzZXRkYnBhcm1zOjprZXlzdG9yZSAtdSAia2V5c3RvcmVwd2QiIC1wIHBhc3N3MHJkCm1xc2lzZXRkYnBhcm1zIC13IC9ob21lL2FjZXVzZXIvYWNlLXNlcnZlciAtbiBsb2NhbDo6YmFzaWNBdXRoT3ZlcnJpZGUgLXUgYWNldXNlciAtcCBjaGFuZ2VpdAo=
